sourceafis.version=${sourceafis.version}
sourceafis.maven.coordinates=com.machinezoo.sourceafis:sourceafis:${sourceafis.version}
sidecar.contract.version=${sidecar.contract.version}
sidecar.implementation.version=${project.version}
